# Generated by Django 4.0.6 on 2025-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrc_data', '0002_reactorstatus_down_date_reactorstatus_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
