# Generated by Django 4.0.6 on 2025-07-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrc_data', '0003_reactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactorstatus',
            name='reactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrc_data.reactor'),
        ),
    ]
