# Generated by Django 4.0.6 on 2025-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrc_data', '0004_reactorstatus_reactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactorstatus',
            name='region',
        ),
        migrations.AlterField(
            model_name='reactor',
            name='region',
            field=models.CharField(choices=[('I', 'Region I'), ('II', 'Region II'), ('III', 'Region III'), ('IV', 'Region IV')], max_length=3),
        ),
    ]
