# Generated by Django 5.2.3 on 2025-07-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrc_data", "0005_remove_reactorstatus_region_alter_reactor_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="StubOutage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_detected", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("auto_detected", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reactor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nrc_data.reactor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReactorForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("df", models.TextField()),
                ("yhat", models.FloatField()),
                ("yhat_lower", models.FloatField()),
                ("yhat_upper", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reactor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nrc_data.reactor",
                    ),
                ),
            ],
            options={
                "unique_together": {("reactor", "created_at")},
            },
        ),
    ]
