# Generated by Django 5.2.3 on 2025-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrc_data", "0007_reactorforecast_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactorforecast",
            name="df",
            field=models.DateField(),
        ),
    ]
