# Generated by Django 4.0.6 on 2025-07-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrc_data', '0009_reactorforecast_reactorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuboutage',
            name='reactorstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nrc_data.reactorstatus'),
        ),
    ]
