# Generated by Django 4.0.6 on 2025-07-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrc_data', '0010_stuboutage_reactorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactorstatus',
            name='reactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactorstatus', to='nrc_data.reactor'),
        ),
    ]
